name: open-draw-build

env:
  APP_NAME: open-draw

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3 # https://github.com/marketplace/actions/docker-setup-qemu

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # https://github.com/marketplace/actions/docker-setup-buildx

      # Enable "Workflow permissions" to "R/W" into https://github.com/thomaschampagne/${repo}/settings/actions
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3 # https://github.com/marketplace/actions/docker-login
        with:
          registry: ghcr.io
          username: ${{ github.action }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version
        run: echo "OCI_VERSION=$(npm run --silent print:version)" >> $GITHUB_ENV

      # Push to GitHub Container Registry
      - name: Push to Github Container Registry
        uses: docker/build-push-action@v6 # https://github.com/marketplace/actions/build-and-push-docker-images
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            APP_NAME=${{ env.APP_NAME}}
            OCI_VERSION=${{ env.OCI_VERSION }}
            OCI_REPO_URL=https://github.com/${{ github.repository }}/tree/${{ github.ref_name }}/${{ env.APP_NAME }}
            OCI_BUILD_DATE=${{ env.BUILD_DATE }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.APP_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.APP_NAME }}:${{ env.OCI_VERSION }}
